#!/usr/bin/env bash

set -eu

source "$PGENV_LIBEXEC"/pgenv--load
source "$PGENV_LIBEXEC"/pgenv--cluster-functions


# Command line options
declare -A options
options=(
  [all]=0
  [opts]=""
  [force]=0
)


# Arguments array
arguments=()


OLDPWD="$PWD"


#: parse_options [arg ...]
#:   Parse command line options.
#:
parse_options() {
  local status=0

  while [ $# -gt 0 ]; do
    case "$1" in
      -a|--all)
        options[all]=1
        ;;
      -o|--options)
        shift
        options[opts]="${options[opts]} $1"
        ;;
      -f|--force)
        options[force]=1
        ;;
      -*)
        abort "error: $(self): invalid option: $1"
        ;;
      *)
        arguments[${#arguments[@]}]="$1"
        ;;
    esac
    shift
  done

  if [ ${options[all]} -eq 0 ]; then
    if [ ${#arguments[@]} -eq 0 ]; then
      error "error: <instance> is not set"
      abort "hint: please set <instance>"
    fi
  fi
}


load_cluster_setting

# Parse command line options.
parse_options "$@"

# Stop my cluster.
if [ ${options[all]} -eq 1 ]; then
  if [ ${options[force]} -eq 1 ]; then
    start_all_instances
  else
    start_cluster
  fi
else
  instance="" status=
  for instance in ${arguments[@]}; do
    if [ ${options[force]} -eq 1 ]; then
      start_instance "$instance" "${options[opts]}" || status=$?
      test $status -ne 0 && log_warn "failed to start instance: $instance"
    else
      start_instance "$instance" "${options[opts]}"
    fi
  done
fi

exit $?


#=begin SUBCOMMAND
#
# cluster start    Start cluster.
#
#=end SUBCOMMAND


#=begin HELP
#
# Usage: pgenv cluster start [-a|--all] [-o <options>] [-f|--force] [<instance>...]
#
# Start cluster.
#
#
# SYNOPSIS
#   pgenv cluster -D /path/to/cluster start --all
#   pgenv cluster -D /path/to/cluster start s1
#
# OPTIONS
#   -a, --all
#     Start all instances.
#
#   -f, --force
#     Even if failed to start an instance, try to start other instances.
#
#   -o, --options <opts>
#     Options passed to 'pg_ctl start' command.
#
#
#=end HELP
